name: 'Swarmpit Service Redeploy Action'
description: 'Redeploy a swarm service through the swarmpit api'
inputs:
  url:
    description: 'Base url of Swarmpit api'
    required: true
  stack:
    description: Stack service belongs to
    required: true
  service:
    description: Service to redeploy inside stack
    required: true
  tag:
    description: Tag to redeploy service with
    required: true
  api-key:
    description: API key to authenticate with Swarmpit API
    required: true

runs:
  using: 'node12'
  main: 'index.js'